# Generated by Django 5.2.7 on 2025-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("local", models.CharField(max_length=200)),
                ("data", models.DateTimeField(verbose_name="data do evento")),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
    ]
