# Generated by Django 5.2.7 on 2025-11-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="eventos_imagens/"
            ),
        ),
    ]
