# Generated by Django 6.0 on 2025-12-05 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_evento_imagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventos_favoritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
