# Generated by Django 6.0 on 2025-12-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_avaliacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacao",
            options={},
        ),
    ]
