# Generated by Django 6.0 on 2025-12-11 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_comentario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receber_emails", models.BooleanField(default=True)),
                (
                    "cidade_padrao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("interesses", models.ManyToManyField(blank=True, to="core.categoria")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
